# Generated by Django 5.2.5 on 2025-08-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallecture",
            name="presentation_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lecture",
            name="presentation_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
