name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y libmagic1
      - name: Install deps
        run: |
          pip install -r requirements.in
          pip install mypy django-stubs flake8 flake8-bugbear
      - name: Lint (flake8)
        run: flake8 .
      - name: Type check (mypy)
        run: mypy .
      - name: Test (pytest)
        env:
          DJANGO_SETTINGS_MODULE: CourseManagement.settings
        run: pytest -q